stm_bm(["menu3100",400,"","../../images/blank.gif",0,"","",0,0,250,0,1000,0,0,0,""],this);
stm_bp("p0",[0,4,0,0,0,2,0,0,100,"progid:DXImageTransform.Microsoft.Fade(overlap=.5,enabled=0,Duration=0.58)",-2,"progid:DXImageTransform.Microsoft.Fade(overlap=.5,enabled=0,Duration=0.58)",-2,52,0,0,"#999999","transparent","",3,0,0,"#999999"]);
stm_ai("p0i0",[0,"    ","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0,0,0,1,"#ffffff",1,"#ffffff",1,"","../../images/bg.gif",3,3,0,0,"#ffffff","#666666","#000000","#000000","9pt Verdana","9pt Verdana",0,0]);
stm_bpx("p1","p0",[1,4,0,4,3,1,16,0,100,"progid:DXImageTransform.Microsoft.Fade(overlap=.5,enabled=0,Duration=0.20)",-2,"progid:DXImageTransform.Microsoft.Fade(overlap=.5,enabled=0,Duration=0.20)",-2,90,2,3,"#999999","#ffffff","",3,1,1]);
stm_aix("p1i0","p0i0",[0,"         ","","",-1,-1,0,"../html/org/info/orgIndex.htm","main","","","../images/icon01.gif","../images/icon01.gif",16,16,0,"","",0,0,0,0,2,"#ffffff",0,"#dfdfdf",0,"","",3,3,1,1,"#ffffff","#666666","#333333"]);
stm_ep();
stm_ep();
stm_aix("p0i1","p0i0",[0,"  BBS  ","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0,0,0,1,"#ffffff",1,"#ffffff",0]);
stm_bpx("p2","p1",[]);
stm_aix("p2i0","p0i0",[0," BBS        ","","",-1,-1,0,"#","_self","","","../images/icon02.gif","../images/icon02.gif",16,16]);
stm_aix("p2i1","p0i0",[0," BBS        ","","",-1,-1,0,"#","_self","","","../images/icon02.gif","../images/icon02.gif",16,16]);
stm_ep();
stm_ep();
stm_aix("p0i2","p0i1",[0,"  �����걨  "]);
stm_bpx("p3","p1",[]);
stm_aix("p3i0","p2i1",[0," �걨�鿴        ","","",-1,-1,0,"../html/media/applicationlist_1.htm","main","","","../images/icon06.gif","../images/icon06.gif"]);
stm_aix("p3i1","p2i1",[0," �걨��ѯ        ","","",-1,-1,0,"../html/media/applicationlist_2.htm","main","","","../images/icon03.gif","../images/icon03.gif"]);
stm_aix("p3i2","p2i0",[0," �걨ͳ��        ","","",-1,-1,0,"#","main","","","../images/icon04.gif","../images/icon04.gif"]);

stm_ep();
stm_aix("p0i3","p0i1",[0,"  ���ڹ���  "]);
stm_bpx("p4","p1",[]);
stm_aix("p4i0","p2i1",[0," ��ٲ鿴        ","","",-1,-1,0,"../html/worktime/leavelist_1.htm","main","","","../images/icon19.gif","../images/icon19.gif"]);
stm_aix("p4i1","p2i0",[0," ��ٲ�ѯ        ","","",-1,-1,0,"../html/worktime/leavelist_2.htm","main","","","../images/icon19.gif","../images/icon19.gif"]);
stm_aix("p4i2","p2i0",[0," ���ͳ��        ","","",-1,-1,0,"#","main","","","../images/icon19.gif","../images/icon19.gif"]);
stm_ep();
stm_aix("p0i4","p0i1",[0,"  ���ʲ�ѯ  "]);
stm_bpx("p5","p1",[]);
stm_aix("p5i0","p2i1",[0," ������ά��        ","","",-1,-1,0,"#","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_bpx("p5","p1",[1,2,3,-4]);
stm_aix("p5i2","p2i0",[0,"����        ","","",-1,-1,0,"../html/wage/provide/export.html","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p5i3","p2i1",[0,"ά��          ","","",-1,-1,0,"../html/wage/provide/wageinfo.html","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_ep();
stm_aix("p5i1","p2i0",[0," ���ʲ�ѯ        "]);
stm_bpx("p5","p1",[1,2,3,-4]);
stm_aix("p5i2","p2i0",[0,"���²�ѯ       ","","",-1,-1,0,"../html/wage/provide/querywagebymonth.html","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p5i3","p2i1",[0,"�����ѯ         ","","",-1,-1,0,"../html/wage/provide/querywagebyitem.html","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p5i3","p2i1",[0,"��������Ϣ��ѯ     ","","",-1,-1,0,"../html/wage/provide/queryotherwageinfo.html","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_ep();
stm_ep();
stm_aix("p0i4","p0i1",[0,"  �ɹ�����  "]);
stm_bpx("p5","p1",[]);
stm_aix("p5i0","p2i1",[0," �ɹ��鿴        ","","",-1,-1,0,"#","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i1","p2i0",[0," �ɹ���ѯ        "]);
stm_aix("p5i2","p2i0",[0," �ɹ�ͳ��        "]);
stm_aix("p5i3","p2i0",[0," ���Ի��ɹ�ͳ��        "]);
stm_ep();
stm_ep();
stm_aix("p0i4","p0i1",[0,"  ���⾭�ѹ���  "]);
stm_bpx("p5","p1",[]);
stm_aix("p5i0","p2i1",[0," �������        ","","",-1,-1,0,"../html/subject/subjectList.html","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i1","p2i0",[0," ������鿴","","",-1,-1,0,"../html/subject/lend/lendList.html","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i2","p2i0",[0," �������ѯ","","",-1,-1,0,"../html/subject/lend/lendList.html","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i3","p2i0",[0," ������ͳ��","","",-1,-1,0,"../html/subject/lend/calc.html","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i3","p2i0",[0," ���ⱨ���鿴","","",-1,-1,0,"../html/subject/baoxiao/baoxiaoList.html","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i3","p2i0",[0," ���ⱨ����ѯ","","",-1,-1,0,"../html/subject/baoxiao/baoxiaoList.html","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i3","p2i0",[0," ���ⱨ��ͳ��","","",-1,-1,0,"../html/subject/baoxiao/baoxiao_calc.html","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_ep();
stm_aix("p0i4","p0i1",[0,"  ҽ�ƾ��ѹ���  "]);
stm_bpx("p5","p1",[]);
stm_aix("p5i0","p2i1",[0," ҽ�Ʊ����鿴        ","","",-1,-1,0,"../html/medical/baoxiao/applist_1.htm","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i1","p2i0",[0," ҽ�Ʊ�����ѯ        ","","",-1,-1,0,"../html/medical/baoxiao/applist_2.htm","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i2","p2i0",[0," ҽ�Ʊ���ͳ��        ","","",-1,-1,0,"#","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i3","p2i0",[0," ҽ�ƽ��鿴        ","","",-1,-1,0,"../html/medical/loan/applist_1.htm","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i3","p2i0",[0," ҽ�ƽ���ѯ        ","","",-1,-1,0,"../html/medical/loan/applist_2.htm","main","","","../images/icon21.gif","../images/icon21.gif"]);
stm_aix("p5i3","p2i0",[0," ҽ�ƽ��ͳ��        ","","",-1,-1,0,"#","main","","","../images/icon21.gif","../images/icon21.gif"]);

stm_ep();
stm_ep();
stm_ep(); 
stm_aix("p0i8","p0i1",[0,"  ��������  "]);
stm_bpx("p15","p1",[]);
stm_aix("p15i0","p2i0",[0,"��������        ","","",-1,-1,0,"../html/bpms/startprocess.htm","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p15i1","p2i0",[0,"��������       ","","",-1,-1,0,"../html/bpms/undo.htm","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p15i2","p2i0",[0,"���̼��       ","","",-1,-1,0,"../html/bpms/monitor.htm","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_ep();

stm_aix("p0i5","p0i1",[0,"  Ȩ�޹���  "]);
stm_bpx("p6","p1",[]);
stm_aix("p6i0","p2i1",[0," ��ɫ����        ","","",-1,-1,0,"../html/pms/rolelist.htm","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p6i1","p2i1",[0," �û�����        ","","",-1,-1,0,"../html/pms/query.htm","main","","","../images/icon20.gif","../images/icon20.gif"]);
stm_ep();
stm_aix("p0i6","p0i1",[0,"  ϵͳ����  "]);
stm_bpx("p7","p1",[]);

stm_aix("p7i3","p2i1",[0," ��������   "]);
stm_bpx("p19","p4",[]);
stm_aix("p1i0","p0i0",[0," ����ά��        ","","",-1,-1,0,"../html/org/info/orgIndex.htm","main","","","../images/icon01.gif","../images/icon01.gif",16,16,0,"","",0,0,0,0,2,"#ffffff",0,"#dfdfdf",0,"","",3,3,1,1,"#ffffff","#666666","#333333"]);
stm_ep();

stm_aix("p7i0","p2i1",[0," ��ѯ����        ","","",-1,-1,0,"../html/org/QUERY/index.html","main","","","../images/icon11.gif","../images/icon11.gif"]);
stm_aix("p7i0","p2i1",[0," ָ�����        ","","",-1,-1,0,"../html/sys/guide/index.html","main","","","../images/icon11.gif","../images/icon11.gif"]);
stm_aix("p7i1","p2i1",[0," �������        ","","",-1,-1,0,"../html/sys/code/index.html","main","","","../images/icon11.gif","../images/icon11.gif"]);
stm_aix("p7i1","p2i1",[0," ��������        ","","",-1,-1,0,"../html/sys/para/index.html","main","","","../images/icon11.gif","../images/icon11.gif"]);

stm_aix("p7i3","p2i1",[0," ��־����        ","","",-1,-1,0,"#","","","","../images/icon12.gif","../images/icon12.gif"]);
stm_bpx("p19","p4",[]);
stm_aix("p19i0","p2i0",[0,"������־    ","","",-1,-1,0,"../html/sys/log/operate-index.jsp","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p19i1","p2i0",[0,"��¼��־    ","","",-1,-1,0,"../html/sys/log/login-index.jsp","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p19i2","p2i0",[0,"��־����   ","","",-1,-1,0,"../html/sys/log/exp-index.jsp","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_ep();

stm_aix("p7i3","p2i1",[0," ���̶��� "]);

stm_bpx("p14","p4",[]);
stm_aix("p14i0","p2i0",[0,"��������б�   ","","",-1,-1,0,"../html/workflow/design/processTypeList.htm","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p14i1","p2i0",[0,"�����б�       ","","",-1,-1,0,"../html/workflow/design/processList.htm","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p14i2","p2i0",[0,"��������б�    ","","",-1,-1,0,"../html/workflow/design/functionTypeList.htm","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p14i3","p2i0",[0,"�����б�        ","","",-1,-1,0,"../html/workflow/design/functionList.htm","main","","","../images/icon08.gif","../images/icon08.gif"]);
stm_aix("p14i4","p2i0",[0,"��������б�    ","","",-1,-1,0,"../html/workflow/design/attachmentTypeList.htm","main","","","../images/icon08.gif","../images/icon08.gif"]);

stm_ep();
stm_ep();
stm_em();
